export const GET_USER_PROFILE_START = 'GET_USER_PROFILE_START';

export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';

export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED';
